const translations={
  es:{navHow:"Cómo funciona",navBeta:"Beta",navDownload:"Descargar",eyebrow:"BETA PARA WINDOWS",heroA:"Jugá más.",heroB:"Jugá mejor.",heroLead:"Tu biblioteca de juegos, tus cuentas de Steam y el catálogo de Game Access en una sola experiencia.",download:"Descargar para Windows",learnMore:"Ver cómo funciona",betaNote:"Acceso beta. Algunas funciones todavía están en desarrollo.",simple:"SIMPLE Y DIRECTO",howTitle:"Entrá. Elegí. Jugá.",step1Title:"Instalá Game Access",step1Body:"Descargá la aplicación para Windows e instalala como cualquier otra app.",step2Title:"Activá tu beta",step2Body:"Ingresá una clave de acceso. La aplicación verifica la vigencia directamente con el servidor.",step3Title:"Explorá tus juegos",step3Body:"Buscá, filtrá, instalá y abrí juegos desde una biblioteca unificada.",betaEyebrow:"ACCESO BETA",betaTitle:"Estamos construyendo Game Access con usuarios reales.",betaBody:"La beta valida el catálogo, las descargas, la activación por tiempo y la integración con Steam antes del lanzamiento público.",beta1:"Activación vinculada a tu instalación.",beta2:"Catálogo y disponibilidad administrados por el servidor.",beta3:"Actualizaciones manuales durante esta etapa.",ready:"LISTO PARA PROBAR",downloadTitle:"Game Access para Windows",requirements:"Requiere Windows 10/11, Steam y conexión a Internet para validar el acceso.",footer:"Beta de desarrollo · Córdoba, Argentina"},
  en:{navHow:"How it works",navBeta:"Beta",navDownload:"Download",eyebrow:"WINDOWS BETA",heroA:"Play more.",heroB:"Play better.",heroLead:"Your game library, your Steam accounts and the Game Access catalog in one experience.",download:"Download for Windows",learnMore:"See how it works",betaNote:"Beta access. Some features are still under development.",simple:"SIMPLE AND DIRECT",howTitle:"Enter. Choose. Play.",step1Title:"Install Game Access",step1Body:"Download the Windows application and install it like any other app.",step2Title:"Activate your beta",step2Body:"Enter an access key. The application verifies its validity directly with the server.",step3Title:"Explore your games",step3Body:"Search, filter, install and launch games from one unified library.",betaEyebrow:"BETA ACCESS",betaTitle:"We are building Game Access with real users.",betaBody:"The beta validates the catalog, downloads, time-based activation and Steam integration before the public launch.",beta1:"Activation is tied to your installation.",beta2:"Catalog and availability are managed by the server.",beta3:"Updates are manual during this stage.",ready:"READY TO TRY",downloadTitle:"Game Access for Windows",requirements:"Requires Windows 10/11, Steam and an Internet connection to validate access.",footer:"Development beta · Córdoba, Argentina"}
};
const supported=["es","en"];
function initialLocale(){const saved=localStorage.getItem("gameaccess:language");if(saved&&supported.includes(saved))return saved;return navigator.language.toLowerCase().startsWith("es")?"es":"en"}
function applyLocale(locale){const lang=supported.includes(locale)?locale:"en";document.documentElement.lang=lang;localStorage.setItem("gameaccess:language",lang);document.querySelectorAll("[data-i18n]").forEach(el=>{const key=el.dataset.i18n;const value=translations[lang][key];if(value)el.textContent=value});document.querySelectorAll("[data-locale]").forEach(button=>button.classList.toggle("active",button.dataset.locale===lang));document.title=lang==="es"?"Game Access — Jugá más y mejor":"Game Access — Play more, play better"}
document.querySelectorAll("[data-locale]").forEach(button=>button.addEventListener("click",()=>applyLocale(button.dataset.locale)));
applyLocale(initialLocale());
