[CmdletBinding()]
param(
    [string]$OutputPath = (Join-Path (Split-Path -Parent $PSScriptRoot) 'assets\media\network-sync-test.ogv'),
    [int]$DurationSeconds = 12,
    [int]$Width = 1280,
    [int]$Height = 720,
    [int]$FrameRate = 30
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$ffmpeg = Get-Command ffmpeg.exe -ErrorAction Stop
$outputDirectory = Split-Path -Parent $OutputPath
New-Item -ItemType Directory -Force -Path $outputDirectory | Out-Null

# testsrc2 is generated by FFmpeg itself, so the fixture is deterministic,
# redistributable and does not introduce third-party media licensing concerns.
$videoFilter = "testsrc2=size=${Width}x${Height}:rate=${FrameRate}"
$audioFilter = 'sine=frequency=440:sample_rate=48000'

$arguments = @(
    '-hide_banner',
    '-loglevel', 'warning',
    '-y',
    '-f', 'lavfi',
    '-i', $videoFilter,
    '-f', 'lavfi',
    '-i', $audioFilter,
    '-t', $DurationSeconds.ToString(),
    '-c:v', 'libtheora',
    '-q:v', '7',
    '-pix_fmt', 'yuv420p',
    '-c:a', 'libvorbis',
    '-q:a', '4',
    '-shortest',
    $OutputPath
)

& $ffmpeg.Source @arguments
if ($LASTEXITCODE -ne 0) {
    throw "FFmpeg exited with code $LASTEXITCODE while generating the sync fixture."
}

$item = Get-Item -LiteralPath $OutputPath
Write-Host "Generated $($item.FullName) ($($item.Length) bytes)"
