from __future__ import annotations

import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "apps" / "desktop" / "src"


def head_bytes(path: str) -> bytes:
    return subprocess.check_output(["git", "show", f"HEAD:{path}"], cwd=ROOT)


# The main completion generator intentionally starts from the old architecture baseline
# so it can extract the large detail renderer. Restore only the CURRENT LibraryRoom
# afterwards: it contains navigation/autoscroll and other unrelated fixes already on
# main, and this Stage 2 detail fix must not regress them.
room_rel = "apps/desktop/src/LibraryRoom.tsx"
(SRC / "LibraryRoom.tsx").write_bytes(head_bytes(room_rel))

# Likewise start LibraryRoomParts from the current main version so selectors used by
# the current LibraryRoom (portrait/wide artwork, etc.) remain available. Remove only
# the superseded MediaPanel/FeaturePanel implementation and re-export the bounded
# LibraryDetailPanel generated by complete_desktop_detail_handoff.py.
parts_rel = "apps/desktop/src/LibraryRoomParts.tsx"
parts = head_bytes(parts_rel).decode("utf-8")
parts = parts.replace(
    'import { Download, Gamepad2, Loader2, Play, ThumbsDown, ThumbsUp, Volume2, VolumeX, XCircle } from "lucide-react";',
    'import { Download, Gamepad2, Loader2, Play, XCircle } from "lucide-react";',
)
parts = parts.replace(
    'import { downloadProgress, formatDownloadBytes, formatDownloadEta, formatDownloadSpeed, isTrackedDownload } from "./downloadManager";',
    'import { isTrackedDownload } from "./downloadManager";',
)
pattern = r'\ninterface MediaPanelProps \{.*?\ninterface CatalogPanelProps'
replacement = '\nexport { FeaturePanel } from "./LibraryDetailPanel";\n\ninterface CatalogPanelProps'
parts, count = re.subn(pattern, replacement, parts, count=1, flags=re.S)
if count != 1:
    raise SystemExit(f"LibraryRoomParts detail extraction: expected one match, got {count}")
(SRC / "LibraryRoomParts.tsx").write_text(parts, encoding="utf-8")

print("Preserved current LibraryRoom navigation/selectors while keeping the generated bounded detail panel.")
